mt-sre/ocm-addons

build_tag.sh
pr_check.sh

Simple change to the build_tag target.

Enable build_tag automation to publish releases

---

.golangci.yaml
.pre-commit-config.yaml
README.md
cmd/ocm-addons/cluster/cmd.go
cmd/ocm-addons/main.go
cmd/ocm-addons/notify/cmd.go
cmd/ocm-addons/notify/cmd_test.go
cmd/ocm-addons/notify/list/cmd.go
cmd/ocm-addons/notify/list/cmd_test.go
go.mod
internal/cli/prompt.go
internal/notification/data/README.md
internal/notification/data/mtsre/managed-odh.yaml
internal/notification/notification.go
internal/notification/notification_test.go
internal/ocm/cluster.go
internal/ocm/log_entry.go
internal/output/table.go

This PR implements subcommands for sending customer notifications to clusters and listing them.

[MTSRE-447] feature: posting customer notifications to clusters

---

.goreleaser.yaml
build_tag.sh
cicd/jenkins_env.sh
magefile.go
pr_check.sh

Refactor CI scripts to promote re-use.

Refactoring CI

---

.github/dependabot.yml
.github/pull_request_template.md
.pre-commit-config.yaml

Making use of GitHub features.

Adding dependabot config and PR template

---

go.mod
go.sum
magefile.go

Ensures go mod tidy runs with `go 1.16` compatibility.
Bug Fix
N/A

Cobra bump from 1.3.0 to 1.4.0

---

magefile.go

Adds `refs` to `pre-commit run` to ensure all changed files are checked.
Docs/Test

Ensure `pre-commit` runs against all changed files

---

CONTRIBUTING.md
README.md
magefile.go
scripts/install.sh

This PR adds some documentation updates and an install utility to facilitate contributions
Docs/Test

Docs for contributors

---

go.mod
go.sum
internal/ocm/addon.go
internal/ocm/addon_test.go

Manually bumping `ocm-sdk-go` since there were changes to the `Addon` data model.
Bug Fix

fix(deps): bump ocm-sdk-go from v0.1.262 to v0.1.264

---

magefile.go

Fixes `release:*` targets to use the cached `goreleaser` binary.
Docs/Test

ci: ensuring goreleaser dependency

---

cmd/ocm-addons/installations/cmd.go
internal/ocm/addon_installation.go
internal/ocm/cluster.go

Expands addon installation table data to include installation version and parameter details.
Bug Fix

[MTSRE-525] Expand addon installation fields

---

cmd/ocm-addons/installations/cmd.go
internal/output/table.go

This PR adds subscription fields for addon installations when requested.
New Feature

[MTSRE-539] feat: adding subscription information to 'addons installations'

---

go.mod
go.sum
integration/generators.go
internal/ocm/cluster.go

Bumps `ocm-sdk-go` to v0.1.278.
Bug Fix

fix(deps): bump ocm-sdk-go to v0.1.278

---

cmd/ocm-addons/cluster/events/cmd.go
cmd/ocm-addons/cluster/info/cmd.go
cmd/ocm-addons/installations/cmd.go
cmd/ocm-addons/list/cmd.go
cmd/ocm-addons/main.go
cmd/ocm-addons/notify/cmd.go
cmd/ocm-addons/notify/list/cmd.go
cmd/ocm-addons/update/cmd.go
cmd/ocm-addons/version/cmd.go
internal/cli/table.go

Makes better use of `Cobra` features.
Bug Fix

fix: improve cobra integration

---

cmd/ocm-addons/main.go
go.mod
internal/cli/run/options.go
internal/cli/run/runner.go
internal/cli/run/signals_posix.go
internal/cli/run/signals_windows.go

Ensure POSIX compliant signal handling.
Bug Fix

fix: ensure proper signal handling for early termination

---

README.md

update git clone link and supported install OS

---

scripts/install.sh

fix: echo system arch

---

README.md

Updating docs to reflect fix introduced by #231.
Docs/Test

docs: remove note indicating lack of support on Mac for install.sh

---

.golangci.yaml
cicd/jenkins_env.sh
cmd/ocm-addons/cluster/info/cmd.go
cmd/ocm-addons/installations/cmd.go
go.mod
internal/ocm/addon_pager_test.go
internal/ocm/addon_request_response.go
internal/ocm/cluster_pager_test.go
internal/ocm/cluster_request_response.go
internal/testutil/command.go
tools/go.mod

Bumps go version to `v1.20`
Bug Fix

Apantuso/bump go v1.20

---

.mise.toml
cicd/jenkins_env.sh
go.mod
tools/go.mod

chore: bump go version to 1.23

---

.github/workflows/test.yaml
flake.nix

chore: add GitHub action for tests

---

.pre-commit-config.yaml

chore: globally exclude vendor files from pre-commit hooks

---

.github/workflows/test.yaml
.pre-commit-config.yaml
Makefile

chore: minor fixes to pr_checks

---

.github/workflows/release.yaml

chore: adding release workflow

---

flake.lock

fix: update flake
